gantt
    title Planejamento - Projeto: Motor Virtual
    dateFormat  DD-MM-YYYY
    axisFormat  %d/%m
    todayMarker off
    
    section Definição
    Definição do Escopo e Problema           :a1, 07-03-2026, 2d
    Diagrama de Blocos                       :a2, after a1, 5d
    Levantamento de Requisitos               :a3, after a1, 18-03-2026
    Entrega da Proposta de Projeto           :milestone, after a3, 0d

    section Desenvolvimento
    Setup BitDogLab                          :b1, after a3, 1d
    Lógica Periféricos                       :b2, after b1, 4d
    Montagem e Testes                        :b3, after b1, 4d

    section Finalização
    Testes Finais                            :c1, after b3, 3d
    Validação                                :c2, after c1, 3d
    Relatório Final                          :c3, after c1, 3d
    Entrega do Projeto                       :milestone, 29-03-2026